import type { Metadata } from "next"; 
import "./globals.css";
import SplashCursor from "@/components/SplashCursor";
import { geistMono, geistSans } from "@/fonts/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SplashCursor/> */}
        
        {children}
      </body>
    </html>
  );
}
